name: Build NDS Port

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up devkitPro
        uses: devkitPro/setup-devkitpro@v1
        with:
          wheels: nds-dev

      - name: Compile SM64 NDS
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=/opt/devkitpro/devkitARM
          make TARGET_NDS=1 VERSION=us -j$(nproc)

      - name: Upload NDS File
        uses: actions/upload-artifact@v4
        with:
          name: sm64-nds-build
          path: build/us_nds/*.nds
